/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class capturemanager_classes_CaptureManagerNativeProxy */

#ifndef _Included_capturemanager_classes_CaptureManagerNativeProxy
#define _Included_capturemanager_classes_CaptureManagerNativeProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
* Class:     capturemanager_classes_CaptureManagerNativeProxy
* Method:    explicitGetPtrClass
* Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
*/
JNIEXPORT jlong JNICALL Java_capturemanager_classes_CaptureManagerNativeProxy_explicitGetPtrClass
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     capturemanager_classes_CaptureManagerNativeProxy
 * Method:    getPtrClass
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT void JNICALL Java_capturemanager_classes_CaptureManagerNativeProxy_freeLibrary
(JNIEnv *, jobject, jstring);

/*
 * Class:     capturemanager_classes_CaptureManagerNativeProxy
 * Method:    Release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_capturemanager_classes_CaptureManagerNativeProxy_Release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
