/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class capturemanager_classes_SessionControlNative */

#ifndef _Included_capturemanager_classes_SessionControlNative
#define _Included_capturemanager_classes_SessionControlNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     capturemanager_classes_SessionControlNative
 * Method:    createSession
 * Signature: (J[JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_capturemanager_classes_SessionControlNative_createSession
  (JNIEnv *, jobject, jlong, jlongArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
