/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class capturemanager_classes_FileSinkFactoryNative */

#ifndef _Included_capturemanager_classes_FileSinkFactoryNative
#define _Included_capturemanager_classes_FileSinkFactoryNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     capturemanager_classes_FileSinkFactoryNative
 * Method:    createOutputNodes
 * Signature: (J[JLjava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_capturemanager_classes_FileSinkFactoryNative_createOutputNodes
  (JNIEnv *, jobject, jlong, jlongArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
