/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class capturemanager_classes_SampleGrabberCallNative */

#ifndef _Included_capturemanager_classes_SampleGrabberCallNative
#define _Included_capturemanager_classes_SampleGrabberCallNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     capturemanager_classes_SampleGrabberCallNative
 * Method:    readData
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_capturemanager_classes_SampleGrabberCallNative_readData
  (JNIEnv *, jobject, jlong, jobject);

JNIEXPORT void JNICALL Java_capturemanager_classes_SampleGrabberCallNative_RGB32ToARGB
(JNIEnv*, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
