/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class capturemanager_classes_SessionNative */

#ifndef _Included_capturemanager_classes_SessionNative
#define _Included_capturemanager_classes_SessionNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     capturemanager_classes_SessionNative
 * Method:    closeSession
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_capturemanager_classes_SessionNative_closeSession
  (JNIEnv *, jobject, jlong);

/*
 * Class:     capturemanager_classes_SessionNative
 * Method:    addIUpdateStateListener
 * Signature: (JLjava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_capturemanager_classes_SessionNative_addIUpdateStateListener
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     capturemanager_classes_SessionNative
 * Method:    getSessionDescriptor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_capturemanager_classes_SessionNative_getSessionDescriptor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     capturemanager_classes_SessionNative
 * Method:    pauseSession
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_capturemanager_classes_SessionNative_pauseSession
  (JNIEnv *, jobject, jlong);

/*
 * Class:     capturemanager_classes_SessionNative
 * Method:    startSession
 * Signature: (JJLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_capturemanager_classes_SessionNative_startSession
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     capturemanager_classes_SessionNative
 * Method:    stopSession
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_capturemanager_classes_SessionNative_stopSession
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
