/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class capturemanager_classes_StrideForBitmapNative */

#ifndef _Included_capturemanager_classes_StrideForBitmapNative
#define _Included_capturemanager_classes_StrideForBitmapNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     capturemanager_classes_StrideForBitmapNative
 * Method:    getStrideForBitmap
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_capturemanager_classes_StrideForBitmapNative_getStrideForBitmap
  (JNIEnv *, jobject, jlong, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
