/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class capturemanager_classes_EncoderNodeFactoryNative */

#ifndef _Included_capturemanager_classes_EncoderNodeFactoryNative
#define _Included_capturemanager_classes_EncoderNodeFactoryNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     capturemanager_classes_EncoderNodeFactoryNative
 * Method:    createCompressedMediaType
 * Signature: (JJLjava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_capturemanager_classes_EncoderNodeFactoryNative_createCompressedMediaType
  (JNIEnv *, jobject, jlong, jlong, jstring, jint, jint);

/*
 * Class:     capturemanager_classes_EncoderNodeFactoryNative
 * Method:    createEncoderNode
 * Signature: (JJLjava/lang/String;IIJ)J
 */
JNIEXPORT jlong JNICALL Java_capturemanager_classes_EncoderNodeFactoryNative_createEncoderNode
  (JNIEnv *, jobject, jlong, jlong, jstring, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
