/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class capturemanager_classes_EVRSinkFactoryNative */

#ifndef _Included_capturemanager_classes_EVRSinkFactoryNative
#define _Included_capturemanager_classes_EVRSinkFactoryNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     capturemanager_classes_EVRSinkFactoryNative
 * Method:    createOutputNode
 * Signature: (JLjava/awt/Component;)J
 */
JNIEXPORT jlong JNICALL Java_capturemanager_classes_EVRSinkFactoryNative_createOutputNode
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
