/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class capturemanager_classes_SampleGrabberCallbackSinkFactoryNative */

#ifndef _Included_capturemanager_classes_SampleGrabberCallbackSinkFactoryNative
#define _Included_capturemanager_classes_SampleGrabberCallbackSinkFactoryNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     capturemanager_classes_SampleGrabberCallbackSinkFactoryNative
 * Method:    createOutputNode
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_capturemanager_classes_SampleGrabberCallbackSinkFactoryNative_createOutputNode
  (JNIEnv *, jobject, jlong, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
