/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class capturemanager_classes_CaptureManagerControlNative */

#ifndef _Included_capturemanager_classes_CaptureManagerControlNative
#define _Included_capturemanager_classes_CaptureManagerControlNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     capturemanager_classes_CaptureManagerControlNative
 * Method:    createControl
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_capturemanager_classes_CaptureManagerControlNative_createControl
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     capturemanager_classes_CaptureManagerControlNative
 * Method:    createMisc
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_capturemanager_classes_CaptureManagerControlNative_createMisc
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
