/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class capturemanager_classes_SinkControlNative */

#ifndef _Included_capturemanager_classes_SinkControlNative
#define _Included_capturemanager_classes_SinkControlNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     capturemanager_classes_SinkControlNative
 * Method:    createSinkFactory
 * Signature: (JLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_capturemanager_classes_SinkControlNative_createSinkFactory
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     capturemanager_classes_SinkControlNative
 * Method:    getCollectionOfSinks
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_capturemanager_classes_SinkControlNative_getCollectionOfSinks
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
