/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class capturemanager_classes_EncoderControlNative */

#ifndef _Included_capturemanager_classes_EncoderControlNative
#define _Included_capturemanager_classes_EncoderControlNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     capturemanager_classes_EncoderControlNative
 * Method:    createEncoderNodeFactory
 * Signature: (JLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_capturemanager_classes_EncoderControlNative_createEncoderNodeFactory
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     capturemanager_classes_EncoderControlNative
 * Method:    getCollectionOfEncoders
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_capturemanager_classes_EncoderControlNative_getCollectionOfEncoders
  (JNIEnv *, jobject, jlong);

/*
 * Class:     capturemanager_classes_EncoderControlNative
 * Method:    getMediaTypeCollectionOfEncoder
 * Signature: (JJLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_capturemanager_classes_EncoderControlNative_getMediaTypeCollectionOfEncoder
  (JNIEnv *, jobject, jlong, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
