/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class capturemanager_classes_LogPrintOutControlNative */

#ifndef _Included_capturemanager_classes_LogPrintOutControlNative
#define _Included_capturemanager_classes_LogPrintOutControlNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     capturemanager_classes_LogPrintOutControlNative
 * Method:    addPrintOutDestinationNative
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_capturemanager_classes_LogPrintOutControlNative_addPrintOutDestinationNative
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     capturemanager_classes_LogPrintOutControlNative
 * Method:    removePrintOutDestinationNative
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_capturemanager_classes_LogPrintOutControlNative_removePrintOutDestinationNative
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     capturemanager_classes_LogPrintOutControlNative
 * Method:    setVerboseNative
 * Signature: (JILjava/lang/String;Ljava/lang/Boolean;)V
 */
JNIEXPORT void JNICALL Java_capturemanager_classes_LogPrintOutControlNative_setVerboseNative
  (JNIEnv *, jobject, jlong, jint, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
