/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class capturemanager_classes_SampleGrabberCallSinkFactoryNative */

#ifndef _Included_capturemanager_classes_SampleGrabberCallSinkFactoryNative
#define _Included_capturemanager_classes_SampleGrabberCallSinkFactoryNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     capturemanager_classes_SampleGrabberCallSinkFactoryNative
 * Method:    createOutputNode
 * Signature: (JLjava/lang/String;Ljava/lang/String;ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_capturemanager_classes_SampleGrabberCallSinkFactoryNative_createOutputNode
  (JNIEnv *, jobject, jlong, jstring, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
